{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "sussy-lib",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.2.jar",
          "url": "sussy-lib-1.0.2.jar",
          "size": 24087,
          "sha512": "7799cb5935bf0e96a6a6c3e4648ae83af69f97852cf0b11b224a6858f8df408ea151b761119b6c32d9f5fdf899196b843ab92ce0dd36b00fbba5a6de9f191850",
          "sha256": "b93dab5f1dc2516eae54abcd1335fa25149cca56184409987df3777ab7e839da",
          "sha1": "7b73b4e2cd540d01e9c517e01d3eaf03c3e041a9",
          "md5": "61ba3dbd48588d111c3dd20ee11ab2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "sussy-lib-1.0.2.jar",
          "url": "sussy-lib-1.0.2.jar",
          "size": 24087,
          "sha512": "7799cb5935bf0e96a6a6c3e4648ae83af69f97852cf0b11b224a6858f8df408ea151b761119b6c32d9f5fdf899196b843ab92ce0dd36b00fbba5a6de9f191850",
          "sha256": "b93dab5f1dc2516eae54abcd1335fa25149cca56184409987df3777ab7e839da",
          "sha1": "7b73b4e2cd540d01e9c517e01d3eaf03c3e041a9",
          "md5": "61ba3dbd48588d111c3dd20ee11ab2c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.2-sources.jar",
          "url": "sussy-lib-1.0.2-sources.jar",
          "size": 14157,
          "sha512": "332edeeec6337a5c6d90e7528ee92936c60c8ef0eb88fe13132d2c7905d79b9744e751128f9b6e76c2252df28b4f8e971a137235be270532b789c47737d31d41",
          "sha256": "57a7b3aad3c358ed764b50b0502ce01e4c6c634c2ab05c18bdd12e23397623b0",
          "sha1": "0dc1180f14fb914dbc066e097645003187817162",
          "md5": "0298dc741ef6baa4a8797d4fd1dce3ab"
        }
      ]
    }
  ]
}
