{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.1.jar",
          "url": "smithees-foundry-1.4.1.jar",
          "size": 759668,
          "sha512": "14c019e65b6c28b192db06a12096d5c8f92819c920ddcdb99ee93343351218f396b0d79cb6ee69c119ab7540113bb4fc1a6a6ce750c681bd87194096ed98ccc5",
          "sha256": "d62a733aa87e71ccee6061c860e8ffb2f452cb8ed6d356a86d49d6338536f321",
          "sha1": "edcd77cda85a6d5e4cc9c10712e6a9baf535fc84",
          "md5": "257bf718020c83a2dd07e9e5c7875c16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.4.1.jar",
          "url": "smithees-foundry-1.4.1.jar",
          "size": 759668,
          "sha512": "14c019e65b6c28b192db06a12096d5c8f92819c920ddcdb99ee93343351218f396b0d79cb6ee69c119ab7540113bb4fc1a6a6ce750c681bd87194096ed98ccc5",
          "sha256": "d62a733aa87e71ccee6061c860e8ffb2f452cb8ed6d356a86d49d6338536f321",
          "sha1": "edcd77cda85a6d5e4cc9c10712e6a9baf535fc84",
          "md5": "257bf718020c83a2dd07e9e5c7875c16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.1-sources.jar",
          "url": "smithees-foundry-1.4.1-sources.jar",
          "size": 551979,
          "sha512": "90886516a46d8965c48345b8a5d03ef9cc4a28ba53c60992522fe498ff8ffba45f7fd609a17e992b9334d97342da34311693d2fcd69aa2147f1184b34affd592",
          "sha256": "9b22aa7545257a607a116d5a54d42fd3ac1ed3877f573397bf6b6eed07b74c75",
          "sha1": "6d1b97c473e56bab7c66d3f5251fa16ff2dda391",
          "md5": "18fbfaddc11fffb178f65cb4436f3194"
        }
      ]
    }
  ]
}
