{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.3.jar",
          "url": "smithees-foundry-1.4.3.jar",
          "size": 798527,
          "sha512": "4edf992911de3a38e6a5e116c8813fde9ed37b5911565719cde7cb0207a595bd4f836d2b43f6c5ea92619a31ebd81ef677ad7962dc62331659cd6c54dc6ff9b1",
          "sha256": "de31061ef0724d3bf872956ea6b57cb23a3e68a36e5d141d495b8b3ccc88a781",
          "sha1": "9fbb8a2ce7b135e70d91c3a6a5ba17091fa838df",
          "md5": "1f5a91cdd5cd7fdd442456310a8ffffb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.4.3.jar",
          "url": "smithees-foundry-1.4.3.jar",
          "size": 798527,
          "sha512": "4edf992911de3a38e6a5e116c8813fde9ed37b5911565719cde7cb0207a595bd4f836d2b43f6c5ea92619a31ebd81ef677ad7962dc62331659cd6c54dc6ff9b1",
          "sha256": "de31061ef0724d3bf872956ea6b57cb23a3e68a36e5d141d495b8b3ccc88a781",
          "sha1": "9fbb8a2ce7b135e70d91c3a6a5ba17091fa838df",
          "md5": "1f5a91cdd5cd7fdd442456310a8ffffb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.3-sources.jar",
          "url": "smithees-foundry-1.4.3-sources.jar",
          "size": 575008,
          "sha512": "3c0ba4aad9b79a57fd8abb1351117ad2c45c9532ad64337c9cb5509c50b494a0bf7e054f723634d55865279e3631369639fc5d3bbf7f70ff77916774559ff7fa",
          "sha256": "e5fd24c19144c991f3b71f8c57de53c057c285da6456dfcd49d3a41691f7d30f",
          "sha1": "b78431523e5c016701cb2ce716f9c83d439ed9d2",
          "md5": "4f1bb8e741a3caaeee63883a29838e2c"
        }
      ]
    }
  ]
}
