{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smcompat",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smcompat-1.0.0.jar",
          "url": "smcompat-1.0.0.jar",
          "size": 47652,
          "sha512": "9521814ccfb244b651b8cd95cee80083d10ed591cd8967c30079a1e798470306e27aa0041d17735ad63cc40e640aa9099c04a7d61a9ef1aa8af2a06107fd749a",
          "sha256": "9de63ec27058be964dbf2eb6adb0fb0b82da37687f2c3404cf7659ef33530834",
          "sha1": "ea2d56b15e8ee1318d068017d0eda2537cf21f5d",
          "md5": "dd1b132400c4652103961b64d6071181"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "smithees-foundry",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smcompat-1.0.0.jar",
          "url": "smcompat-1.0.0.jar",
          "size": 47652,
          "sha512": "9521814ccfb244b651b8cd95cee80083d10ed591cd8967c30079a1e798470306e27aa0041d17735ad63cc40e640aa9099c04a7d61a9ef1aa8af2a06107fd749a",
          "sha256": "9de63ec27058be964dbf2eb6adb0fb0b82da37687f2c3404cf7659ef33530834",
          "sha1": "ea2d56b15e8ee1318d068017d0eda2537cf21f5d",
          "md5": "dd1b132400c4652103961b64d6071181"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smcompat-1.0.0-sources.jar",
          "url": "smcompat-1.0.0-sources.jar",
          "size": 30062,
          "sha512": "549902c2569a818a95a76bfdfce9d75d237cc3b853e0188ef82ecfb70c7320a3b2fa5a1cc0ae6dbb6c1db8c8d3ee7bf45fb4337ef2e598c31e0a651691a58718",
          "sha256": "f36c683a931e1ea49003c1cb243c38a93ad7de2cbce03c196a8690cd7b7a2766",
          "sha1": "96cbeaec4838fc0da1f5b4678510cde8a92bfe36",
          "md5": "2a0d509332fd872b16e56658d0cdee66"
        }
      ]
    }
  ]
}
