{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.3.jar",
          "url": "smithees-foundry-1.3.3.jar",
          "size": 690376,
          "sha512": "41a60a73efadda21dd8312871758998af1e338d964db85a92def502acf26719876a20d7d0821fb2de4533bf6e5df3478b0c90aa3eab90877f9f0464f2beff64f",
          "sha256": "cc0184ac24ab8c9d0b43642dfc0660d9c6ca02522b9b89452ba41bf479540ee5",
          "sha1": "ead839ea56098a103e677a6ce530ff8a9fce5454",
          "md5": "773189e669a1e1b57ad24b7202fb9ef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.3.3.jar",
          "url": "smithees-foundry-1.3.3.jar",
          "size": 690376,
          "sha512": "41a60a73efadda21dd8312871758998af1e338d964db85a92def502acf26719876a20d7d0821fb2de4533bf6e5df3478b0c90aa3eab90877f9f0464f2beff64f",
          "sha256": "cc0184ac24ab8c9d0b43642dfc0660d9c6ca02522b9b89452ba41bf479540ee5",
          "sha1": "ead839ea56098a103e677a6ce530ff8a9fce5454",
          "md5": "773189e669a1e1b57ad24b7202fb9ef5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.3-sources.jar",
          "url": "smithees-foundry-1.3.3-sources.jar",
          "size": 506280,
          "sha512": "c1515e63fd5583729fe1507fd1686a23ba4e70b8fd926bb34fcf52fdee5ce0d498b73bc439dcc492822271ae7436272db655faed2778eb8ce3e58e9544e760f8",
          "sha256": "0b6ac122b1d1c437e4744798a126a5925965af3de67064b64a058503c0e588e6",
          "sha1": "c453883f48998cbd8f61554e29dff3ceb99f546d",
          "md5": "9d49e0a2484b2d4b951139dd25c68161"
        }
      ]
    }
  ]
}
