{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smcompat",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smcompat-1.2.2.jar",
          "url": "smcompat-1.2.2.jar",
          "size": 71775,
          "sha512": "639ed8ebb610cb27bd43c5ae92b9fb3e2e2ba78259fd49150c379b7c8053f347282ff7e09cd362421f677cb9eedf94ecb3ade520efb655fe196dab14d4e6228c",
          "sha256": "f4344e8ad76f5e400fc4b2c48108be19452ea917665a3c0f67959386a948b99e",
          "sha1": "26304052bd4d3d83afc198228cff05b01313e008",
          "md5": "fcfdc79bf8f0c6cad996f56606d75fba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smcompat-1.2.2.jar",
          "url": "smcompat-1.2.2.jar",
          "size": 71775,
          "sha512": "639ed8ebb610cb27bd43c5ae92b9fb3e2e2ba78259fd49150c379b7c8053f347282ff7e09cd362421f677cb9eedf94ecb3ade520efb655fe196dab14d4e6228c",
          "sha256": "f4344e8ad76f5e400fc4b2c48108be19452ea917665a3c0f67959386a948b99e",
          "sha1": "26304052bd4d3d83afc198228cff05b01313e008",
          "md5": "fcfdc79bf8f0c6cad996f56606d75fba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smcompat-1.2.2-sources.jar",
          "url": "smcompat-1.2.2-sources.jar",
          "size": 42703,
          "sha512": "6b11a05c0e668bf504065bda4a9b89c1fe72833b67b420dea2d5067c523b59af22eb32f9dd27ba605cca66c2b6cdbb4b2a01676b5f5953c9667d1a14f66af1f9",
          "sha256": "fa5911d9923143bf18d57d997443c68abfc51d7f02509de4b3493cabe86c6603",
          "sha1": "3b4b9635f5c83ac8aa329d6fa92e6ebc84921ab6",
          "md5": "4be45397a00e902b4d89a5304874e93a"
        }
      ]
    }
  ]
}
