{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.2.jar",
          "url": "smithees-foundry-1.4.2.jar",
          "size": 760711,
          "sha512": "eeb5097839239468965c7abd4c84cb8446967a3bca8052f29eda51417519634a2334aa3d2968f99e839b3eb0bc3788dc62b388e86f7ce4ea0b55244224f05416",
          "sha256": "04f02a6ed8f670bbd2896ca0703cde46ce51095c6a3e4dd3637d68fd72ee55b3",
          "sha1": "c02d4c1afb9dc010d828eca03f753fd27c99ab9f",
          "md5": "0eb38a37e939e797bf49f34e0a5297da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.4.2.jar",
          "url": "smithees-foundry-1.4.2.jar",
          "size": 760711,
          "sha512": "eeb5097839239468965c7abd4c84cb8446967a3bca8052f29eda51417519634a2334aa3d2968f99e839b3eb0bc3788dc62b388e86f7ce4ea0b55244224f05416",
          "sha256": "04f02a6ed8f670bbd2896ca0703cde46ce51095c6a3e4dd3637d68fd72ee55b3",
          "sha1": "c02d4c1afb9dc010d828eca03f753fd27c99ab9f",
          "md5": "0eb38a37e939e797bf49f34e0a5297da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.4.2-sources.jar",
          "url": "smithees-foundry-1.4.2-sources.jar",
          "size": 552173,
          "sha512": "62c93718ab75ca0327967c668438629ae3080841bc42610815b8b49f460afd101a0f8d2712f4cc948249361bf834d2a90e999c7cb2adf1967dbbf34de2e8a197",
          "sha256": "76041c01ed14793b19f8525ffb8b6bf53885e8b2b423c62a9167a449438838b6",
          "sha1": "1ed703cff5b6efec0d085b82b675c101c8b11078",
          "md5": "819429db83a20b36885407841f6e4025"
        }
      ]
    }
  ]
}
