{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "the-forge",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-forge-1.2.1.jar",
          "url": "the-forge-1.2.1.jar",
          "size": 574877,
          "sha512": "54f5889edb03361e5d67ae552a2414ea55cf31976cba14778ceaf604aa2ba83b366d6a6830012269bdc3bfdfb9e3a3fb5568a979d3e23d9ccf5d381e6949fa00",
          "sha256": "617a41942af6e4b9505e76a4378d08d021d55f794606e7c6e04223a15c7e3c55",
          "sha1": "78520b35f23531e1ff35f1d60b673a8bd8f0b157",
          "md5": "d13a4f2dedf35338432ba8210c2578fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "the-forge-1.2.1.jar",
          "url": "the-forge-1.2.1.jar",
          "size": 574877,
          "sha512": "54f5889edb03361e5d67ae552a2414ea55cf31976cba14778ceaf604aa2ba83b366d6a6830012269bdc3bfdfb9e3a3fb5568a979d3e23d9ccf5d381e6949fa00",
          "sha256": "617a41942af6e4b9505e76a4378d08d021d55f794606e7c6e04223a15c7e3c55",
          "sha1": "78520b35f23531e1ff35f1d60b673a8bd8f0b157",
          "md5": "d13a4f2dedf35338432ba8210c2578fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "the-forge-1.2.1-sources.jar",
          "url": "the-forge-1.2.1-sources.jar",
          "size": 420186,
          "sha512": "f46c64c9a01d00b25be7c69c877092bf095f407db3b48bf13c4bad8b5fde6afecd440a5631ae4f268e30352571cd2e8f2067ad0be937c5e3bff875caed7dca92",
          "sha256": "399a60c7bc03b290ce73999cbf2188a54fa0d26601baecbb85a160843d13920d",
          "sha1": "cb102747ecb92222377703ad9b4c7069a8fef0b6",
          "md5": "c010806197669c6db0715e65e879bcba"
        }
      ]
    }
  ]
}
