{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "sussyconfig",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sussyconfig-1.0.0.jar",
          "url": "sussyconfig-1.0.0.jar",
          "size": 7744,
          "sha512": "e5b0ac5160bc346045eb01a156ecc58c0030b2feb1d28af04e762d188be76aee6673bbecd3c3cd8bd703d55c3d39c35cbcfd0df8f2513c8e7e1e9157f5501432",
          "sha256": "e008fd2f0a0ee15b8f68032b870a860ae3c29ff0e6f8f389b758924d2dd5c19a",
          "sha1": "cb639527f296eff7a8fa35f1ff6f6ecb1adcf634",
          "md5": "3addff2880331a6ceb33a47df33994df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.47.8+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "sussyconfig-1.0.0.jar",
          "url": "sussyconfig-1.0.0.jar",
          "size": 7744,
          "sha512": "e5b0ac5160bc346045eb01a156ecc58c0030b2feb1d28af04e762d188be76aee6673bbecd3c3cd8bd703d55c3d39c35cbcfd0df8f2513c8e7e1e9157f5501432",
          "sha256": "e008fd2f0a0ee15b8f68032b870a860ae3c29ff0e6f8f389b758924d2dd5c19a",
          "sha1": "cb639527f296eff7a8fa35f1ff6f6ecb1adcf634",
          "md5": "3addff2880331a6ceb33a47df33994df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sussyconfig-1.0.0-sources.jar",
          "url": "sussyconfig-1.0.0-sources.jar",
          "size": 4482,
          "sha512": "2e086a42799ba40c9d523e915d8a54b6b9aa6c64a19722fa62557e3d93f818cab7fb85948147943ac3aad9418f04aeae88c66a4655043838dc109ec0be444935",
          "sha256": "187024c909ff3eeddd47d5b154264648e9bf2bbae0707d6625b12e1bf90f3a9f",
          "sha1": "8cb058642f64c23926a2ecb9b43ca5e3246da72c",
          "md5": "b341ef115fb86e698faa022519608172"
        }
      ]
    }
  ]
}
