{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.0.jar",
          "url": "smithees-foundry-1.3.0.jar",
          "size": 617657,
          "sha512": "9c016129f65a3431928ac9f5f093694ecbc5a54052b854753ff30b717513394ad0ac66dca025424f939971ae734c383b56e04d936258882440b9308e6cd31be8",
          "sha256": "31d09b9d4c95313bd953742ad2c754dabe59b4d50946a36af5be3c7d222fe557",
          "sha1": "25082e955505f0823601d9bf8e81d383bb4f6367",
          "md5": "5e3e3a9c73ca27f8afdc125a9a95956e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.3.0.jar",
          "url": "smithees-foundry-1.3.0.jar",
          "size": 617657,
          "sha512": "9c016129f65a3431928ac9f5f093694ecbc5a54052b854753ff30b717513394ad0ac66dca025424f939971ae734c383b56e04d936258882440b9308e6cd31be8",
          "sha256": "31d09b9d4c95313bd953742ad2c754dabe59b4d50946a36af5be3c7d222fe557",
          "sha1": "25082e955505f0823601d9bf8e81d383bb4f6367",
          "md5": "5e3e3a9c73ca27f8afdc125a9a95956e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.0-sources.jar",
          "url": "smithees-foundry-1.3.0-sources.jar",
          "size": 453807,
          "sha512": "267174dda03280f20fd9951ba760513aea1f6e18b31e508fc881e45c2239f942b59d98d1af041bbe6a58e025fdc548d2609dd5e01afcd8bfb98da9863f835462",
          "sha256": "8f1bf37e047232a6995a6829277251727d6ce925b0b5a5b6982a7bc98a8ef2a8",
          "sha1": "f67ee4a7fa494b64b14bd065b5d0e3b09772938d",
          "md5": "e8e725f098fdfcf1271ec28a2bbba379"
        }
      ]
    }
  ]
}
