{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.1.jar",
          "url": "smithees-foundry-1.2.1.1.jar",
          "size": 582284,
          "sha512": "4335d89729c08c8b21fbd970bc587c08d4ac62ecfd2743e268c90ffdc621975ef1ba1aff8b31c044965b264d4ca0d60bf71a881cad0b953db4f0d989994d18eb",
          "sha256": "70abbcd764c5a27f904fb76f168be7b6ae2ea132ab5a7b166bd2964374ac186a",
          "sha1": "cd7ba00b7e9a56857520ea695886c89b536becc6",
          "md5": "4c90739a2f71598f91107a96a58d92e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.2.1.1.jar",
          "url": "smithees-foundry-1.2.1.1.jar",
          "size": 582284,
          "sha512": "4335d89729c08c8b21fbd970bc587c08d4ac62ecfd2743e268c90ffdc621975ef1ba1aff8b31c044965b264d4ca0d60bf71a881cad0b953db4f0d989994d18eb",
          "sha256": "70abbcd764c5a27f904fb76f168be7b6ae2ea132ab5a7b166bd2964374ac186a",
          "sha1": "cd7ba00b7e9a56857520ea695886c89b536becc6",
          "md5": "4c90739a2f71598f91107a96a58d92e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.1-sources.jar",
          "url": "smithees-foundry-1.2.1.1-sources.jar",
          "size": 426569,
          "sha512": "80b811702e2f25187e5943c5a8f650d39d3d6d2416709005fb597e7a4559fee71a9dc514a34bcb43a0a1997c2370d102247ec5d642b37ee9b8e5910bea34d1d2",
          "sha256": "0e4f173a74d2714d106f6cce36bb7941517b377cedf25517a02d34ea2dc216ab",
          "sha1": "f30332753494312a8c801c46ffffc523fb0bb5c4",
          "md5": "0e5cf39bcda1def2a6411dfe438e41cd"
        }
      ]
    }
  ]
}
