{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "sussy-lib",
    "version": "1.0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.3.2.jar",
          "url": "sussy-lib-1.0.3.2.jar",
          "size": 47634,
          "sha512": "9ffd48737b2b9a1601b09a956dcbbaa94dd8202f72a6591f2b9c81c52f8f732e0e8b10bfa3f59f8e0f9c3c2b9f26966746139b01cbc38a0880cb597e332cd603",
          "sha256": "e0d3bb1ed5c097757e8bf5decba49daacee2185cda026d2d65f60565e021194e",
          "sha1": "19915a3a9be983fa5871d20732cd1fa638d93587",
          "md5": "e1929fb03850b2ee8fb81f8f87d7721e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "sussy-lib-1.0.3.2.jar",
          "url": "sussy-lib-1.0.3.2.jar",
          "size": 47634,
          "sha512": "9ffd48737b2b9a1601b09a956dcbbaa94dd8202f72a6591f2b9c81c52f8f732e0e8b10bfa3f59f8e0f9c3c2b9f26966746139b01cbc38a0880cb597e332cd603",
          "sha256": "e0d3bb1ed5c097757e8bf5decba49daacee2185cda026d2d65f60565e021194e",
          "sha1": "19915a3a9be983fa5871d20732cd1fa638d93587",
          "md5": "e1929fb03850b2ee8fb81f8f87d7721e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.3.2-sources.jar",
          "url": "sussy-lib-1.0.3.2-sources.jar",
          "size": 37669,
          "sha512": "b9ade56febfcb9b8e4a6e6b95376f31f70ea598e8054956e52fcac0ad5f81c6e4b070c613998315833cc6eea49574a2d2631869db3957f698d74a9ad4f5c6336",
          "sha256": "e4faca03dcca0dd3c6f94f27c6a48dd1fd3fe62b5e8d3ee27e82641157e1c8c1",
          "sha1": "be8c5e4faced01237a84c7b1a4664f1c03f057df",
          "md5": "249fcfa33f2963e0a755a805cc038506"
        }
      ]
    }
  ]
}
