{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "the-forge",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-forge-1.2.0.jar",
          "url": "the-forge-1.2.0.jar",
          "size": 570052,
          "sha512": "d16b0408c6e78d73f3c739d4d39c6efa1be0c1c1ef9438b652e1af122bb922d61f73067fb597f9096fcaed049a42b677ea8e3c700a9b96abd45ed1d9906db667",
          "sha256": "61a3e68b5aef0f3b5ac30e7e8519f4ed7a18578abb0404f12b38643b76e7b197",
          "sha1": "c8dbbb584bd03754e1af0ca8db881a5ff5212e32",
          "md5": "8f67bbb1941f797abb7a4c8a0e575179"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "the-forge-1.2.0.jar",
          "url": "the-forge-1.2.0.jar",
          "size": 570052,
          "sha512": "d16b0408c6e78d73f3c739d4d39c6efa1be0c1c1ef9438b652e1af122bb922d61f73067fb597f9096fcaed049a42b677ea8e3c700a9b96abd45ed1d9906db667",
          "sha256": "61a3e68b5aef0f3b5ac30e7e8519f4ed7a18578abb0404f12b38643b76e7b197",
          "sha1": "c8dbbb584bd03754e1af0ca8db881a5ff5212e32",
          "md5": "8f67bbb1941f797abb7a4c8a0e575179"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "the-forge-1.2.0-sources.jar",
          "url": "the-forge-1.2.0-sources.jar",
          "size": 416486,
          "sha512": "a11786bcf398528b06524768eff3651ba2ff524cc93b9650eb9745f6f77d3ebef281bf4cbf63f05962fa34cbfdf815b22b1e4a7da3df28774bff94698dbf80cc",
          "sha256": "2982b644ede661307c08d1a747a125c96aecf833766085054e6f5744e86b6549",
          "sha1": "5c2bd2c4471389f2beec4e37e8bfdd8319d2dbe5",
          "md5": "dfefba05f461f3f82afb98788337fbdd"
        }
      ]
    }
  ]
}
