{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.6.0-1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.6.0-1.19.3.jar",
          "url": "smithees-foundry-1.6.0-1.19.3.jar",
          "size": 1140842,
          "sha512": "173ce62fa6c8abd16e240bddb9e3d3374f7b43df3b1696ace759c00ff4f8e241bc229bb95e5d93904de480f656316da9ba45bd40db71c4c1ae5218c34e6d14aa",
          "sha256": "22f14a7785a823164e1b90afabe82b8a54dfbeec0c982e644abfc2b6292e3254",
          "sha1": "a8da8a728f434f428cb804360373948041bf7cf5",
          "md5": "8d16821550b36383369f5c5af5068246"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.0+1.19.3"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussy-lib",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.6.0-1.19.3.jar",
          "url": "smithees-foundry-1.6.0-1.19.3.jar",
          "size": 1140842,
          "sha512": "173ce62fa6c8abd16e240bddb9e3d3374f7b43df3b1696ace759c00ff4f8e241bc229bb95e5d93904de480f656316da9ba45bd40db71c4c1ae5218c34e6d14aa",
          "sha256": "22f14a7785a823164e1b90afabe82b8a54dfbeec0c982e644abfc2b6292e3254",
          "sha1": "a8da8a728f434f428cb804360373948041bf7cf5",
          "md5": "8d16821550b36383369f5c5af5068246"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.6.0-1.19.3-sources.jar",
          "url": "smithees-foundry-1.6.0-1.19.3-sources.jar",
          "size": 776333,
          "sha512": "21b6798fc801e8d2794b3908eadd5b7a9cfc5a529017d011364c06d0f08f2985b4373d20172c08eb6d24ea6d7478f5f8acd47176b69b72d2383122c8be7c0051",
          "sha256": "555f4422289edc3cc90c5ff2c88af137292b7bede4fa2734c07c0cc1b592341a",
          "sha1": "c9403caf6ec9046f6c80c127db5b230d5acb2150",
          "md5": "e14b4e96554ba25263376299f3b4de85"
        }
      ]
    }
  ]
}
