{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.0.1.jar",
          "url": "smithees-foundry-1.3.0.1.jar",
          "size": 618988,
          "sha512": "1a274b36b292860c66db210b417c435e01ef37f07b9530802f70c329928faa66d8d3169adca20a059391462f906016b74e0d4c8716b93a0afd49b26f5a39a3c0",
          "sha256": "f4db6438f13738fd6b635e47a96c4d60258eb68f2fcef35c0c829d0a6716eeca",
          "sha1": "3d7ea17501b4fe66841fe306bb128fb035fcffad",
          "md5": "49af805e0b2339d2acc6956a9277c533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.3.0.1.jar",
          "url": "smithees-foundry-1.3.0.1.jar",
          "size": 618988,
          "sha512": "1a274b36b292860c66db210b417c435e01ef37f07b9530802f70c329928faa66d8d3169adca20a059391462f906016b74e0d4c8716b93a0afd49b26f5a39a3c0",
          "sha256": "f4db6438f13738fd6b635e47a96c4d60258eb68f2fcef35c0c829d0a6716eeca",
          "sha1": "3d7ea17501b4fe66841fe306bb128fb035fcffad",
          "md5": "49af805e0b2339d2acc6956a9277c533"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.0.1-sources.jar",
          "url": "smithees-foundry-1.3.0.1-sources.jar",
          "size": 455028,
          "sha512": "b6687d7063f925a2e1b816bcfc4a89f1675a00af234bcdfd6f2848a7c5dafe6956c3d68c74af6559a1ff6dbdaa8750906cf81e334c0351750e16562f0d4b8499",
          "sha256": "4460509a30df8ad726f77a85093bbda29dc6656a253ec2358aeb106d5b5254bd",
          "sha1": "ed3a1478ea8cf4aa3812cdd90be9badd706efc3b",
          "md5": "4626c4c7d5aaf988e211678657c55554"
        }
      ]
    }
  ]
}
