{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.2.1.jar",
          "url": "smithees-foundry-1.3.2.1.jar",
          "size": 668831,
          "sha512": "52d3d1aa6e193c1a97fc4e97b1f2201f5dfca919e9385da72c92dcf75873044ccb0eb1feaa427bb911383ac72fa2049a1f5c0dc9301a431d6a9599184640b1b1",
          "sha256": "2c6b21f79af3f0cad8ababae478655007566f9b32e70683672812408f341d5d9",
          "sha1": "95bd64322ad9f9ab7ead2f5b00968cf3b0a46429",
          "md5": "5dcc273dd042fcc3294bc27b38e3b29c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.3.2.1.jar",
          "url": "smithees-foundry-1.3.2.1.jar",
          "size": 668831,
          "sha512": "52d3d1aa6e193c1a97fc4e97b1f2201f5dfca919e9385da72c92dcf75873044ccb0eb1feaa427bb911383ac72fa2049a1f5c0dc9301a431d6a9599184640b1b1",
          "sha256": "2c6b21f79af3f0cad8ababae478655007566f9b32e70683672812408f341d5d9",
          "sha1": "95bd64322ad9f9ab7ead2f5b00968cf3b0a46429",
          "md5": "5dcc273dd042fcc3294bc27b38e3b29c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.3.2.1-sources.jar",
          "url": "smithees-foundry-1.3.2.1-sources.jar",
          "size": 490048,
          "sha512": "57ecb524eb585f99281461f57c90c3a453b201cf3838b83aa34134b71be34d95ccb76cc508fbc300a6728aad56ccb52662a62cf63d342def40eea5284e162c52",
          "sha256": "d1ea8f4dce97958f0651e7d86d39c7996caab796e978a5758be776c32f2a6f23",
          "sha1": "63b6478efecb732bd92049897f88d00402d70051",
          "md5": "46cfcf1d2f8ca2a857d8f50eb83c8442"
        }
      ]
    }
  ]
}
