{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "sussy-lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.0.jar",
          "url": "sussy-lib-1.0.0.jar",
          "size": 24080,
          "sha512": "f204bdda0903d0667b251ed8e78ff1047bf84b35541d030118a7b8094373e754b9db3677c4536737912ffe2c42867a3c2b38cc5e2fc1a15686c94a28eb0a9c7d",
          "sha256": "41c96797969aadbfe0e735115f01074c5286e54f902d32d78515725fd05af67a",
          "sha1": "6a00cfff304e32b2bf3f8a74ba1967b714085bb6",
          "md5": "2efcfea70708c4977af89377d7865a15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "sussy-lib-1.0.0.jar",
          "url": "sussy-lib-1.0.0.jar",
          "size": 24080,
          "sha512": "f204bdda0903d0667b251ed8e78ff1047bf84b35541d030118a7b8094373e754b9db3677c4536737912ffe2c42867a3c2b38cc5e2fc1a15686c94a28eb0a9c7d",
          "sha256": "41c96797969aadbfe0e735115f01074c5286e54f902d32d78515725fd05af67a",
          "sha1": "6a00cfff304e32b2bf3f8a74ba1967b714085bb6",
          "md5": "2efcfea70708c4977af89377d7865a15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sussy-lib-1.0.0-sources.jar",
          "url": "sussy-lib-1.0.0-sources.jar",
          "size": 14054,
          "sha512": "ad29c48f31a929f7a09c4671d5d7940a0bf8b8f507ce6e15c1efb00e0d04c4b0493b57433701d3dd9b0a4790cafd6f9ff52bcb5a0ffeb3ea624ca07b2593c957",
          "sha256": "cdc629867758cfdc008dd6a9efe0a5ded3c97c609ba96a7917e36ddfc2930412",
          "sha1": "f48f80515a7b208c151fd82bbd079e0bb8b3cecc",
          "md5": "b83c9463e5f78ec1e82a3a0118c0f26a"
        }
      ]
    }
  ]
}
