{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.2.jar",
          "url": "smithees-foundry-1.5.2.jar",
          "size": 1022503,
          "sha512": "d880d8c9d660cb07b5840910aeffd0e699e5861981c296045558d6a4d289b57aa8b28cc6ed50216c5ee0cf3848ca06f205def7375f35c475e93a994487be95b4",
          "sha256": "5b30fa29d770bbb62dce457ec3540ac5558187687f1c724f99442ec9d8cbf723",
          "sha1": "bc406a0a0e615809e6227953ff7259bce6de3fba",
          "md5": "0a5c4e3066f85967092e77fef48499f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.5.2.jar",
          "url": "smithees-foundry-1.5.2.jar",
          "size": 1022503,
          "sha512": "d880d8c9d660cb07b5840910aeffd0e699e5861981c296045558d6a4d289b57aa8b28cc6ed50216c5ee0cf3848ca06f205def7375f35c475e93a994487be95b4",
          "sha256": "5b30fa29d770bbb62dce457ec3540ac5558187687f1c724f99442ec9d8cbf723",
          "sha1": "bc406a0a0e615809e6227953ff7259bce6de3fba",
          "md5": "0a5c4e3066f85967092e77fef48499f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.2-sources.jar",
          "url": "smithees-foundry-1.5.2-sources.jar",
          "size": 715752,
          "sha512": "7c9f0bf54fece2fc149ceb8233004cbdbea7df62effce1bce7c774df86f9b8abb1526c641647b3b8a04ca977caa118533062c9d8ad43df2f94e9f4cdf7c5302e",
          "sha256": "763f3f42891076e97565be05eee54a8ed7f067c020b6248b51b4c6a8f493023f",
          "sha1": "b512d0417067eb4519d29f554d655f9af3a71e8e",
          "md5": "dd4e6371c875389414e44bdb5043013b"
        }
      ]
    }
  ]
}
