{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0.jar",
          "url": "smithees-foundry-1.5.0.jar",
          "size": 1653692,
          "sha512": "90a9f06784a91e3e4b92354f447eb0e82abea29ea350eaaf4b77d9053f015b64f0913e7ca2871312a55e33c410173eead270572806fdae84fee90141e0579c8f",
          "sha256": "f42792e1d536e50aef99579fcecf152b58dce28e6ea3c1df383c55e3aae3fb2d",
          "sha1": "28959e1c35b20b056a107b68237984482ce1384e",
          "md5": "9d4fc06ff54b3431d532fb4771a50df0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.5.0.jar",
          "url": "smithees-foundry-1.5.0.jar",
          "size": 1653692,
          "sha512": "90a9f06784a91e3e4b92354f447eb0e82abea29ea350eaaf4b77d9053f015b64f0913e7ca2871312a55e33c410173eead270572806fdae84fee90141e0579c8f",
          "sha256": "f42792e1d536e50aef99579fcecf152b58dce28e6ea3c1df383c55e3aae3fb2d",
          "sha1": "28959e1c35b20b056a107b68237984482ce1384e",
          "md5": "9d4fc06ff54b3431d532fb4771a50df0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0-sources.jar",
          "url": "smithees-foundry-1.5.0-sources.jar",
          "size": 648577,
          "sha512": "8fffcc5b67d817cac458629d8f8374bc0f3a5da2081c86aabf4af103e02c2eb908e78d5f3daa16c244670249e11c6ce115600efce36572afc905008afd9e0505",
          "sha256": "6f3b9471cc6463293e27cc5015efe520d8cd23761fc48727c44c2c615d86e9dc",
          "sha1": "3eb3b0d1a390884f9b4719295aac79060b937a16",
          "md5": "eaa03d1d4b729b4c7ffbe46753e6890f"
        }
      ]
    }
  ]
}
