{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0.jar",
          "url": "smithees-foundry-1.5.0.jar",
          "size": 986414,
          "sha512": "ec189f378fb4c9d06149b317e02f6e7d10c41a0b47ca7ebd8ab323a4a14dfbd816525ba2facca308c5facb68d08084129f14872cee077ea69bcfe25b6c1fc02c",
          "sha256": "bc5cdd1604ad6e10d524eebaadfdbe7c6994f136cbbfa3db919b623e4c687fb8",
          "sha1": "c9881208d2638c0ac0c132cfae24334ed33367c1",
          "md5": "886e1829f3687f26a887500ed826da5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.5.0.jar",
          "url": "smithees-foundry-1.5.0.jar",
          "size": 986414,
          "sha512": "ec189f378fb4c9d06149b317e02f6e7d10c41a0b47ca7ebd8ab323a4a14dfbd816525ba2facca308c5facb68d08084129f14872cee077ea69bcfe25b6c1fc02c",
          "sha256": "bc5cdd1604ad6e10d524eebaadfdbe7c6994f136cbbfa3db919b623e4c687fb8",
          "sha1": "c9881208d2638c0ac0c132cfae24334ed33367c1",
          "md5": "886e1829f3687f26a887500ed826da5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0-sources.jar",
          "url": "smithees-foundry-1.5.0-sources.jar",
          "size": 699483,
          "sha512": "02d46d4c2669bb119938a50041131113f71b7ee78917cfd7e25169963b72046a37dbf8628663ca8084bd54e05ee16217d14cca1c7fcd10148026959a54f965cd",
          "sha256": "e33dde1b07d9d34586c0639143d5730177c98d6534ee7e242eb3baf85e938b5f",
          "sha1": "1cfaba6448214f112df0add3a6ec8457bb9ba29d",
          "md5": "7832678459ca5af6f159c38d17672e43"
        }
      ]
    }
  ]
}
