{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smcompat",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smcompat-1.2.1.jar",
          "url": "smcompat-1.2.1.jar",
          "size": 61820,
          "sha512": "3181c0ff1f3cedada493e272883b1b5677125ac937fbd928e32d9e5cd5c1fce746b116525927ed4584f9425585eab96a772e3ce187eaa2ceeaa2b135a3d5ad94",
          "sha256": "895d3cb5590687ef03ebd9875b9cf9216ee998ca1cab23491737ad26e538c10f",
          "sha1": "830332904e4936cb61501eb35e61e694d7fafd0c",
          "md5": "86c43b460e0606532027c5b8d6e2f72e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smcompat-1.2.1.jar",
          "url": "smcompat-1.2.1.jar",
          "size": 61820,
          "sha512": "3181c0ff1f3cedada493e272883b1b5677125ac937fbd928e32d9e5cd5c1fce746b116525927ed4584f9425585eab96a772e3ce187eaa2ceeaa2b135a3d5ad94",
          "sha256": "895d3cb5590687ef03ebd9875b9cf9216ee998ca1cab23491737ad26e538c10f",
          "sha1": "830332904e4936cb61501eb35e61e694d7fafd0c",
          "md5": "86c43b460e0606532027c5b8d6e2f72e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smcompat-1.2.1-sources.jar",
          "url": "smcompat-1.2.1-sources.jar",
          "size": 40065,
          "sha512": "bc237a59d2df8313538852c7695da7a6a5be348afb4d255c6c32be64c62c26d517472d050af31d923296700bae69026f2cf6151674da45f5bf43352601cbad6b",
          "sha256": "febfcb4378b51c9efbc255a022f95a89ac4387bf2fc52b7a58f62c34fe7ca467",
          "sha1": "ba44fe20dcc6f57c8e1972d3eede6a2b0bb75b4a",
          "md5": "526277a53476440f58d3653c2769d8bd"
        }
      ]
    }
  ]
}
