{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "the-forge",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-forge-0.0.1.jar",
          "url": "the-forge-0.0.1.jar",
          "size": 292306,
          "sha512": "56015e8e02bb8ed1d6006b6df2af53a00191fbc05fb9b83e51bc2f01d1cc94f41de0c93472a139805d654d71b49743767b73c38cf1f30915fb5e8c7e2aaefaed",
          "sha256": "f8ccdbc641b4f8659fef1a1ccaf95f030121c44263e0e67688b2b3f6fce82b65",
          "sha1": "d31b6433960e9651dc04a9a2d524a35f03c7cfca",
          "md5": "e424e27dd7fb97c4332a5439aded9f73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.53.4+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "the-forge-0.0.1.jar",
          "url": "the-forge-0.0.1.jar",
          "size": 292306,
          "sha512": "56015e8e02bb8ed1d6006b6df2af53a00191fbc05fb9b83e51bc2f01d1cc94f41de0c93472a139805d654d71b49743767b73c38cf1f30915fb5e8c7e2aaefaed",
          "sha256": "f8ccdbc641b4f8659fef1a1ccaf95f030121c44263e0e67688b2b3f6fce82b65",
          "sha1": "d31b6433960e9651dc04a9a2d524a35f03c7cfca",
          "md5": "e424e27dd7fb97c4332a5439aded9f73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "the-forge-0.0.1-sources.jar",
          "url": "the-forge-0.0.1-sources.jar",
          "size": 209569,
          "sha512": "65ea744c9110a8ae512ad14edd252cc1efe2c2a018494402980a3350461dbbca16fc8c1a8b6360e7ed4c5a3910c9ea81506e824173ab7e69e6a1ede509a4dbd0",
          "sha256": "e0f546b22dedee54af2a45bd6f9b9c5266ad4c1549ff909de5ad677c0a6c53ef",
          "sha1": "eb8d74e8d0161fe8e65407ff09629de4db1778f9",
          "md5": "300a0736dd5ae3788e7fb46f19ab2b42"
        }
      ]
    }
  ]
}
