{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.2.jar",
          "url": "smithees-foundry-1.2.1.2.jar",
          "size": 588045,
          "sha512": "524c70351247627cd6a51fea92c18e13d2b33a6e624a40691ea7ef98386f979d35884336a33dd7048662bafe295dfcf953ef10b01e234364608f6127768bfc72",
          "sha256": "26bec4dbb939b5c690aab2ddb8fb686aab62c488178d87ce3ef3fa3b67ddeef2",
          "sha1": "82a944218a212836bd8e295e9c80fa815b255624",
          "md5": "1b33387c2b769c86a60ea70a76e64517"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.2.1.2.jar",
          "url": "smithees-foundry-1.2.1.2.jar",
          "size": 588045,
          "sha512": "524c70351247627cd6a51fea92c18e13d2b33a6e624a40691ea7ef98386f979d35884336a33dd7048662bafe295dfcf953ef10b01e234364608f6127768bfc72",
          "sha256": "26bec4dbb939b5c690aab2ddb8fb686aab62c488178d87ce3ef3fa3b67ddeef2",
          "sha1": "82a944218a212836bd8e295e9c80fa815b255624",
          "md5": "1b33387c2b769c86a60ea70a76e64517"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.2-sources.jar",
          "url": "smithees-foundry-1.2.1.2-sources.jar",
          "size": 428418,
          "sha512": "7e7ca364a3bbfe1620b580b3e1bb21bfd462bf1d245ca68c4102648211b35291ce5d9a887e92dc60bbe969d336a29683d57cccf210a87e09bff118e52bbffc77",
          "sha256": "ccd9826848a27880e4ca2457e4a5131fc50dbdc45962c6df236863ad742783c2",
          "sha1": "02851eb11141d645d822d3d5eed51e13370fba71",
          "md5": "d75aecfa2cb3510eb6f69715c71ba412"
        }
      ]
    }
  ]
}
