{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "the-forge",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-forge-1.0.0.jar",
          "url": "the-forge-1.0.0.jar",
          "size": 296289,
          "sha512": "ea442997b1434d1eb15238aec2705c65263ae1feca933725ad42bd4152620e415f046e0a4c00f3543d1709490f1f725e910f201acf2fe257a482ac7e89de9ebd",
          "sha256": "0a8288d81d2bc93270262328ebf05b18a47da9034f7c158e0d52d6347c310a8d",
          "sha1": "0c0d3f1e48cc4b47c3683b39ce1145c96b264daa",
          "md5": "e234238d9f28a7daa986feb352bf2715"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.53.4+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "the-forge-1.0.0.jar",
          "url": "the-forge-1.0.0.jar",
          "size": 296289,
          "sha512": "ea442997b1434d1eb15238aec2705c65263ae1feca933725ad42bd4152620e415f046e0a4c00f3543d1709490f1f725e910f201acf2fe257a482ac7e89de9ebd",
          "sha256": "0a8288d81d2bc93270262328ebf05b18a47da9034f7c158e0d52d6347c310a8d",
          "sha1": "0c0d3f1e48cc4b47c3683b39ce1145c96b264daa",
          "md5": "e234238d9f28a7daa986feb352bf2715"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "the-forge-1.0.0-sources.jar",
          "url": "the-forge-1.0.0-sources.jar",
          "size": 212126,
          "sha512": "9bdfac29543069415b5a494bcbedcaf9d2d46b4daa2ef26a37016298c3a97f789d18b53b477872019122e3384c75b28a1318f0d645229988a9e33d62a6143311",
          "sha256": "2be45ca99304b51c48918773336181d93ac3a651f2d3c452324d476cba94956f",
          "sha1": "4adf9cfe33b6638ed67ae54453b2c3ba158ddb39",
          "md5": "09afde45b74b4591a6038d9ca0403adf"
        }
      ]
    }
  ]
}
