{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "the-forge",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-forge-1.1.0.jar",
          "url": "the-forge-1.1.0.jar",
          "size": 315729,
          "sha512": "db0804ccfabfe67be0d9aa949dd2def7840b45177ada33910f5bb4baf53b09c8d5dd5ff7639e02c5c53c46cb9efe6136605ff95db2bc5980cf890b81d81e36c2",
          "sha256": "a1b16e017a873873fec596d3d1d49e9ba7cd53ba46d6c0b30d77de43d612bd37",
          "sha1": "2260829707fd0f7d93edf66252ce651d6d8ddba3",
          "md5": "a5b6fac62fc4bce182d91b01d9643a61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.53.4+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "the-forge-1.1.0.jar",
          "url": "the-forge-1.1.0.jar",
          "size": 315729,
          "sha512": "db0804ccfabfe67be0d9aa949dd2def7840b45177ada33910f5bb4baf53b09c8d5dd5ff7639e02c5c53c46cb9efe6136605ff95db2bc5980cf890b81d81e36c2",
          "sha256": "a1b16e017a873873fec596d3d1d49e9ba7cd53ba46d6c0b30d77de43d612bd37",
          "sha1": "2260829707fd0f7d93edf66252ce651d6d8ddba3",
          "md5": "a5b6fac62fc4bce182d91b01d9643a61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "the-forge-1.1.0-sources.jar",
          "url": "the-forge-1.1.0-sources.jar",
          "size": 231550,
          "sha512": "58b9f522de21db735d33bd95770ffceaac3102177f21259fe42a3ade657aa4496575ef9565c3ab0abbacf7b6d468e50ba3cfc92a3f8fca5f45a3911551ddf50f",
          "sha256": "a8844758210f6516a1e8a83300e4a78a3a7487f54b70ab0df13ee9eef4a849cf",
          "sha1": "7d5666d2cd2d74b61ea9e2d74596b8b2a7a631d5",
          "md5": "65acdba463ddc11eacfd77f80f1cb80d"
        }
      ]
    }
  ]
}
