{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0-SNAPSHOT.jar",
          "url": "smithees-foundry-1.5.0-SNAPSHOT.jar",
          "size": 1653606,
          "sha512": "ac6ddfa1740d847d82f3039aed3f25bbc5503f6028d8093c589ca4d859471db896f3d900683062bcb1249a9e6a3eede3d826bf080764a7dabdf56272ac3c4f3a",
          "sha256": "62e52fed52cdfc8c5f2596b3ecd9c7d997556c4f8fbadddb72ad79686b010d1c",
          "sha1": "f59d12e798e418f42633b17d5fe1aeb12bedfc87",
          "md5": "7c7b0a692ca2744d635d7c2235d6a341"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.5.0-SNAPSHOT.jar",
          "url": "smithees-foundry-1.5.0-SNAPSHOT.jar",
          "size": 1653606,
          "sha512": "ac6ddfa1740d847d82f3039aed3f25bbc5503f6028d8093c589ca4d859471db896f3d900683062bcb1249a9e6a3eede3d826bf080764a7dabdf56272ac3c4f3a",
          "sha256": "62e52fed52cdfc8c5f2596b3ecd9c7d997556c4f8fbadddb72ad79686b010d1c",
          "sha1": "f59d12e798e418f42633b17d5fe1aeb12bedfc87",
          "md5": "7c7b0a692ca2744d635d7c2235d6a341"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.5.0-SNAPSHOT-sources.jar",
          "url": "smithees-foundry-1.5.0-SNAPSHOT-sources.jar",
          "size": 648532,
          "sha512": "878ce666d6bfcf54ac780d72bef1b46c458a154dbd1a7c9bba77c670d6fd219e73631a152110618e0825a4e8296d2514ae55c576754bb7b7753f8defb6e99ec2",
          "sha256": "22413bc785cbf3b96204bc908d1f09a6a9ee1fc846f7d17b17e95f1f30f4dafe",
          "sha1": "75dd5d07b33f21cca856ccaf966e767ddf5dc927",
          "md5": "9cf9705416312ddbc9889bdc187be3ce"
        }
      ]
    }
  ]
}
