{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sussysyrup",
    "module": "smithees-foundry",
    "version": "1.2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.3.jar",
          "url": "smithees-foundry-1.2.1.3.jar",
          "size": 589889,
          "sha512": "60d299ede2721b89a9ab16cbe423d70092b1eebc0b709174cb632d063e6ef00280e94f24188ccaad03033c3a282038981c9b44000b776402c2139afb5e122b75",
          "sha256": "6018982f87ed25d6274cb4b2a84d7548f04964a55b7f7bcf36399be838d6c287",
          "sha1": "36d5a3d79ab817b9954b578486a49aeacc34e8f8",
          "md5": "e16ac1be726a4ee029b70f66272f40e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.57.0+1.18.2"
          }
        },
        {
          "group": "com.sussysyrup",
          "module": "sussyconfig",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.18.2-70-FABRIC"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "8.2.471"
          }
        }
      ],
      "files": [
        {
          "name": "smithees-foundry-1.2.1.3.jar",
          "url": "smithees-foundry-1.2.1.3.jar",
          "size": 589889,
          "sha512": "60d299ede2721b89a9ab16cbe423d70092b1eebc0b709174cb632d063e6ef00280e94f24188ccaad03033c3a282038981c9b44000b776402c2139afb5e122b75",
          "sha256": "6018982f87ed25d6274cb4b2a84d7548f04964a55b7f7bcf36399be838d6c287",
          "sha1": "36d5a3d79ab817b9954b578486a49aeacc34e8f8",
          "md5": "e16ac1be726a4ee029b70f66272f40e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smithees-foundry-1.2.1.3-sources.jar",
          "url": "smithees-foundry-1.2.1.3-sources.jar",
          "size": 429434,
          "sha512": "3bf03fd363d4e9c8f34834a93aa7b30a0eba889f3e9ed58d13feb546c4706b8501eb744a46ce4a563c86b998d80e1f52c729b4be3ccc22d975ef403a284f58f2",
          "sha256": "aa74f67faf9f8a45d785f1f3df0ab3db5762a2a631e7ba1f61993c72f127398c",
          "sha1": "a7feb9bd57a50c40a0599403c5cd7a36bfbde166",
          "md5": "07c19fcb6f098a8d78b310df4d19ac4e"
        }
      ]
    }
  ]
}
